trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 1

# 1. Aceptar licencias del Android SDK y NDK
- script: |
    chmod +x gradlew
    yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
  displayName: 'Aceptar términos del NDK y SDK'

# 2. Compilar APK y AAB (Debug, sin firmar manualmente)
- task: Gradle@3
  displayName: 'Generar APK y AAB Debug'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleDebug bundleDebug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'

# 3. Colectar archivos para descarga
- task: CopyFiles@2
  displayName: 'Organizar archivos generados'
  inputs:
    Contents: |
      **/*-debug.apk
      **/*-debug.aab
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

# 4. Publicar Artefactos en Azure Pipelines
- task: PublishBuildArtifacts@1
  displayName: 'Publicar para descarga'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Android_Builds'
